config/routes.rb
Rails.application.routes.draw do


  namespace :api do
    namespace :v1 do
      resources :articles
    end
  end

devise_for :users, controllers: { sessions: 'users/sessions' }

  root "articles#welcome"

  resources :articles do
    resources :comments
  end
  get 'welcome', to: 'welcome#index', as: 'welcome'


get '/about_me', to: 'articles#about_me', as: 'about_me'
get '/home', to: 'articles#index', as: 'home'




get 'modern_home', to: 'modern_home#index', as: 'modern_home'
get 'about_me_modern', to: 'modern_home#about_me_modern', as: 'about_me_modern'
get 'modern_articles/new', to: 'modern_home#new_modern_article', as: 'new_modern_article'
get 'show_modern/:id', to: 'modern_home#show_modern', as: 'show_modern'

get 'modern_articles', to: 'modern_articles#index', as: 'modern_articles'
get 'modern_articles/:id', to: 'modern_articles#show', as: 'modern_article'






get 'funny_home', to: 'funny_home#index', as: 'funny_home'
get 'about_me_funny', to: 'funny_home#about_me_funny', as: 'about_me_funny'
get 'new_funny_article', to: 'funny_home#new_funny_article', as: 'new_funny_article'
get 'show_funny/:id', to: 'funny_home#show_funny', as: 'show_funny'






end

app/models/account.rb
class Account < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  has_one_attached :image
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern
  
    VALID_STATUSES = ['public', 'private', 'archived']
  
    included do
      validates :status, inclusion: { in: VALID_STATUSES }
    end
  
    class_methods do
      def public_count
        where(status: 'public').count
      end
    end
  
    def archived?
      status == 'archived'
    end
  end
  

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/modern_article.rb
class ModernArticle < ApplicationRecord
    include Visible
    has_one_attached :image
    has_many :comments, dependent: :destroy
  
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 5 }
  end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_one_attached :profile_picture
  end
  

app/controllers/api_controller.rb
class ApiController < ApplicationController
    
    before_action :http_authenticate
    rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
    private
    def http_authenticate
      authenticate_or_request_with_http_basic do |email, password|
        user = User.find_by(email: email)
        user && user.valid_password?(password)
      end
    end
    def record_not_found
      render json: { error: 'Record not found' }, status: :not_found
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :last_name, :first_name, :profile_picture])
      end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found 

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new 
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end


  def about_me
    @about_me_content = "Je suis [votre nom], et je suis passionné(e) par [vos intérêts]."
  end
 

 private

  def record_not_found
    flash[:alert] = 'Record not found'
    redirect_to root_path
  end

  def article_params
    params.require(:article).permit(:title, :body, :image, :status)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "yassmine", password: "yassmine", only: :destroy
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: :see_other
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end
end

app/controllers/funny_home_controller.rb
class FunnyHomeController < ApplicationController
  def index
    @articles = Article.all
    render 'funny_home/index'
  end

  def new_funny_article
    @article = Article.new
  end
end

app/controllers/modern_articles_controller.rb
  
  class ModernArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new 
  end


  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  def about_me
    @about_me_content = "Je suis [votre nom], et je suis passionné(e) par [vos intérêts]."
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :image, :status)
  end
end

app/controllers/modern_home_controller.rb
class ModernHomeController < ApplicationController
  
  def index
    @articles = Article.all
    render 'modern_home/index'
  end


  def new_modern_article
    @article = Article.new
    render 'modern_home/new_modern_article'

  end
 
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
# app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        redirect_to root_path

    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/funny_home/about_me_funny.html.erb
<body style="background-color: #f5c4b8;">

  <div class="flex flex-col items-stretch w-full" style="min-width:450px">

    <nav class="flex justify-between items-center py-4  -mt-32 rounded-3xl text-white w-full h-40" style="background-color:#426a5a;">
    <div class="flex items-center">

    <% if current_user.profile_picture.attached? %>
    <%= image_tag current_user.profile_picture, alt: 'Image de profil', class: "rounded-full w-28 h-28" %>
    <% else %>
      <%= image_tag('logofun.png', alt: 'Image par défaut', class: "rounded-full") %>
    <% end %>

      </div>
      
      

      <% if user_signed_in?  %>


      <div class="text-white -ml-60 text-3xl italic" style="font-family: 'URW Chancery L', cursive;">
       <%= "#{current_user.username} #{current_user.last_name}" %>
     </div>

      <div class="mr-6"style=" min-width:75px;">
      <%= link_to "Welcome ", welcome_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
      </div>


      <div class="mr-6"style=" min-width:65px;">
      <%= link_to "Home ", funny_home_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
      </div>

      <div class="mr-6"style=" min-width:120px;">
      <%= link_to "About Us", about_me_funny_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
      </div>
      <%end%>
    </nav>





<div  style=" font-size:100px; color: #426a5a; margin-top:70px ; text-shadow:20px 20px 15px white">
   <h1>Ayari Yassmine <br> a software student </h1>
</div>



  <div class="-mt-10" style=" margin-left:auto; width:500px">
  <%= image_tag('mind.png', alt: 'Image de livre') %>
</div>




    </div>

app/views/funny_home/index.html.erb
<body style="background-color: #f5c4b8;">

  <div class="flex flex-col items-stretch w-full" style="min-width:450px">

    <nav class="flex justify-between items-center py-4  -mt-32 rounded-3xl text-white w-full h-40" style="background-color:#426a5a;">
    <div class="flex items-center">

    <% if current_user.profile_picture.attached? %>
    <%= image_tag current_user.profile_picture, alt: 'Image de profil', class: "rounded-full w-28 h-28" %>
    <% else %>
      <%= image_tag('logofun.png', alt: 'Image par défaut', class: "rounded-full w-20 h-20 ml-2" ) %>
    <% end %>

      </div>
      
      

      <% if user_signed_in?  %>


      <div class="text-white -ml-60 text-3xl italic" style="font-family: 'URW Chancery L', cursive; margin-left:-2%">
       <%= "#{current_user.username} #{current_user.last_name}" %>
     </div>

      <div class="mr-6"style=" min-width:65px;">
      <%= link_to "Welcome ", welcome_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
      </div>


      <div class="mr-6"style=" min-width:65px;">
      <%= link_to "New ", new_funny_article_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
      </div>


      <div class="mr-6" style="min-width:115.6px" >
        <%= link_to "Edit Profile", edit_user_registration_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
     </div>
     <div class="mr-6" style="min-width:115.6px" >
     <%= link_to "Sign Out", destroy_user_session_path, method: :delete , class: "border border-white rounded-full py-2 px-4 text-white" , style:"; margin-right:auto; "  %>

    </div>

 
    <%end%>
    
    </nav>



    <div class="flex flex-wrap mt-4 ">
    <ul class="flex-2 flex flex-wrap">
      <% @articles.each do |article| %>
        <% unless article.archived? %>
        <li class="inline-block border border-black rounded-3xl p-4 mb-8 mr-4 ml-14 mt-8 bg-white" style="width: 400px; height: 450px; position: relative;">
            <div style="position: absolute; top: 0; left: 50%; transform: translateX(-50%);">
            </div>
           <% if article.image.attached? %>
              <%= image_tag article.image, class: "rounded-3xl mx-auto", style: "max-height: 200px; display: block; margin: 0 auto;" %>
            <% end %>
           
            <div class="text-gray-700 text-sm text-center mt-20">
            <%= link_to article.title, modern_article_path(article), class: "text-xl text-center block " %>
            <br>
              <% if params[:full] == 'true' %>
                <%= article.body %>
              <% else %>
                <%= truncate(article.body, length: 20) %><br><br>
                <%= link_to 'Show More', article_path(article, full: true), class: "font-semibold text-base border border-black box-border rounded-md text-center", style: "display: block; margin: 0 auto; width:140px; height:40px; padding-top:2%" %>
              <% end %>
            </div>
          </li>
        <% end %>
      <% end %>

      <div class="absolute top-0 left-0 mt-20" style="margin-left: 7.3%;">
      <%= image_tag('take.png', alt: 'Image de livre', style: " width: 550px; height: auto;") %>
    </div>
    

    </ul>
  </div>


  <div class="w-96 -mt-6" style=" margin-left:auto">
  <%= image_tag('here.png', alt: 'Image de livre') %>
</div>



<!--
<div class="w-96 top-0 absolute right-0 mt-20 ml-4">
<%= image_tag('take.png', alt: 'Image de livre') %>
</div>

-->


    </div>

app/views/funny_home/new_funny_article.html.erb
<body style="background-color: #f5c4b8;">

  <div class="flex flex-col items-stretch w-full" style="min-width:450px">

    <nav class="flex justify-between items-center py-4  -mt-32 rounded-3xl text-white w-full h-40" style="background-color:#426a5a;">
    <div class="flex items-center">

    <% if current_user.profile_picture.attached? %>
    <%= image_tag current_user.profile_picture, alt: 'Image de profil', class: "rounded-full w-28 h-28" %>
    <% else %>
      <%= image_tag('logofun.png', alt: 'Image par défaut', class: "rounded-full") %>
    <% end %>

      </div>
      
      

      <% if user_signed_in?  %>


      <div class="text-white -ml-60 text-3xl italic" style="font-family: 'URW Chancery L', cursive;">
       <%= "#{current_user.username} #{current_user.last_name}" %>
     </div>

      <div class="mr-6"style=" min-width:65px;">
      <%= link_to "Welcome ", welcome_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
      </div>


      <div class="mr-6"style=" min-width:65px;">
      <%= link_to "Home ", funny_home_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
      </div>

      <div class="mr-6"style=" min-width:120px;">
      <%= link_to "About Us", about_me_funny_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
      </div>
      <%end%>
    </nav>




    <div class="mt-20 md:-mt-2 md:ml-20 lg:-mt-20 lg:ml-96" style="width: 300px; ">
    <%= image_tag('editt.png', alt: 'Image de livre') %>
  </div>
  


    <div class=" border border-black  border-2 rounded-3xl bg-white  mx-auto  " style=" width:600px; height:500px; ">
    <div class="flex flex-col items-center justify-center h-full">
    
    <h1 class="text-center -mt-22 italic text-3xl font-semibold " style="text-shadow:20px 10px 5px black ;font-family: 'URW Chancery L', cursive;">New Article</h1>
    
    <%= render "form_article_funny", article: @article %>
    
     </div>
    
     </div>
    
    
    





    </div>

app/views/modern_home/about_me_modern.html.erb
<body style="background-color: #bee9e8;">

  <div class="flex flex-col items-stretch w-full" style="min-width:450px">

    <nav class="flex justify-between items-center py-4  -mt-32 rounded-3xl text-white w-full h-40" style="background-color:#468faf;">
    <div class="flex items-center">

    <% if current_user.profile_picture.attached? %>
    <%= image_tag current_user.profile_picture, alt: 'Image de profil', class: "rounded-full w-28 h-28" %>
    <% else %>
      <%= image_tag('profile.jpg', alt: 'Image par défaut', class: "rounded-full") %>
    <% end %>

      </div>
      
      

      <% if user_signed_in?  %>


      <div class="text-white -ml-60 text-3xl italic" style="font-family: 'URW Chancery L', cursive;">
       <%= "#{current_user.username} #{current_user.last_name}" %>
     </div>

      <div class="mr-6"style=" min-width:65px;">
      <%= link_to "Welcome ", welcome_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
      </div>

      <div class="mr-6"style=" min-width:65px;">
      <%= link_to "Home", modern_home_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
    </div>
    
    <div class="mr-6"style=" min-width:120px;">
    <%= link_to "About Us", about_me_modern_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
    </div>
    <%end%>
    </nav>


<br>

<div style="position: relative; ">
  <%= image_tag('laptop.png', alt: 'Image de livre', class: 'mx-auto md:-ml-60', style: 'margin-left:auto; width:750px; height:750px; margin-top:-10px') %>

  <div class="border border-transparent rounded-3xl" style="position: absolute; top: 30%; left: 49.8%; transform: translate(-50%, -50%); width: 300px; max-width: 400px; height: 160px; background-color: #2d2e2e;">
    <div class="flex flex-col items-center justify-center h-full">
      <h1 class="text-white text-3xl text-left italic" style="">Yassmine Ayari <br> A software <br> engineering student </h1>
    </div>

    <!--
   <div class="w-60 " style="">
     <%= image_tag('signature.png', alt: 'Image de livre',class:'w-96 mx-auto rounded-xl ', style:'margin-left:80%; margin-top:-42%') %>
   </div>
-->
  </div>
</div>






  </div>

  </body>

app/views/modern_home/index.html.erb
<body style="background-color: #bee9e8;">

  <div class="flex flex-col items-stretch w-full" style="min-width:450px">

    <nav class="flex justify-between items-center py-4  -mt-32 rounded-3xl text-white w-full h-40" style="background-color:#468faf;">
    <div class="flex items-center">

    <% if current_user.profile_picture.attached? %>
    <%= image_tag current_user.profile_picture, alt: 'Image de profil', class: "rounded-full w-28 h-28" %>
    <% else %>
      <%= image_tag('profile.jpg', alt: 'Image par défaut', class: "rounded-full w-20 h-20 ml-2") %>
    <% end %>

      </div>
     
      <% if user_signed_in?  %>

      <div class="text-white text-3xl italic" style="font-family: 'URW Chancery L', cursive; margin-left:-2%">
        <%= "#{current_user.username} #{current_user.last_name}" %>
      </div>

    
     <div class="mr-6"style=" min-width:65px;">
     <%= link_to "Welcome ", welcome_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
     </div>

      <div class="mr-6"style=" min-width:65px;">
      <%= link_to "New ", new_modern_article_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
      </div>

      <div class="mr-6" style="min-width:115.6px" >
        <%= link_to "Edit Profile", edit_user_registration_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
     </div>
     <div class="mr-6" style="min-width:115.6px" >
     <%= link_to "Sign Out", destroy_user_session_path, method: :delete , class: "border border-white rounded-full py-2 px-4 text-white" , style:"; margin-right:auto; "  %>

    </div>

    <% else%> 
    
      <div class="mr-6">
       <%= link_to "Sign Up", new_user_registration_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
      </div>
  
      <div class="mr-6">
        <%= link_to "Sign In", new_user_session_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
      </div>

    <%end%>
    </nav>



    <div class="flex flex-wrap mt-4 ">
    <ul class="flex-2 flex flex-wrap">
      <% @articles.each do |article| %>
        <% unless article.archived? %>
          <li class="inline-block border border-black rounded-3xl p-4 mb-8 mr-4 ml-14 mt-8 bg-white" style="width: 400px; height:450px; position: relative;">
            <div style="position: absolute; top: 0; left: 50%; transform: translateX(-50%);">
            </div>
           <% if article.image.attached? %>
              <%= image_tag article.image, class: "rounded-3xl mx-auto", style: "max-height: 200px; display: block; margin: 0 auto;" %>
            <% end %>
           
            <div class="text-gray-700 text-sm text-center mt-20">
            <%= link_to article.title, article_path(article), class: "text-xl text-center block" , style: ""%>
            <br>
              <% if params[:full] == 'true' %>
                <%= article.body %>
              <% else %>
                <%= truncate(article.body, length: 20) %><br><br>
                <%= link_to 'Show More', article_path(article, full: true), class: "font-semibold text-base border border-black box-border rounded-md text-center", style: "display: block; margin: 0 auto; width:140px; height:40px; padding-top:2%" %>
              <% end %>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>



  <div class="w-96 ml-6 mt-8">
  <%= image_tag('robot1.png', alt: 'Image de livre') %>
</div>

<div class="w-96 top-0 absolute right-0 mt-20 ml-4">
<%= image_tag('robot2.png', alt: 'Image de livre') %>
</div>

    </div>


    

app/views/modern_home/new_modern_article.html.erb
<body style="background-color: #bee9e8;">

  <div class="flex flex-col items-stretch w-full" style="min-width:600px">

    <nav class="flex justify-between items-center py-4  -mt-32 rounded-3xl text-white w-full h-40" style="background-color:#468faf;">
    <div class="flex items-center">

    <% if current_user.profile_picture.attached? %>
    <%= image_tag current_user.profile_picture, alt: 'Image de profil', class: "rounded-full w-28 h-28" %>
    <% else %>
      <%= image_tag('profile.jpg', alt: 'Image par défaut', class: "rounded-full") %>
    <% end %>

      </div>
      
      

      <% if user_signed_in?  %>


      <div class="text-white -ml-60 text-3xl italic" style="font-family: 'URW Chancery L', cursive;">
       <%= "#{current_user.username} #{current_user.last_name}" %>
     </div>

      <div class="mr-6"style=" min-width:65px;">
      <%= link_to "Welcome ", welcome_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
      </div>


      
      <div class="mr-6"style=" min-width:65px;">
      <%= link_to "Home", modern_home_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
    </div>
    
    <div class="mr-6"style=" min-width:120px;">
    <%= link_to "About Us", about_me_modern_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
    </div>
    <%end%>
    </nav>




<br>


<div class=" border border-black  border-2 rounded-3xl bg-white  mx-auto  " style=" width:600px; height:600px;  ">
<div class="flex flex-col items-center justify-center h-full">

<h1 class="text-center -mt-22 italic text-3xl font-semibold " style="text-shadow:20px 10px 5px black ;font-family: 'URW Chancery L', cursive;">New Article</h1>

<%= render "form_article_modern", article: @article %>

 </div>

 </div>


 <div class="mt-20 md:-mt-2 md:ml-20 lg:-mt-96 lg:-ml-20" style="width: 500px;">
  <%= image_tag('robot.png', alt: 'Image de livre') %>
</div>




</div>
</body>

app/views/modern_home/show_modern.html.erb
<body style="background-color: #bee9e8;">

  <div class="flex flex-col items-stretch w-full">

    <nav class="flex justify-between items-center py-4  -mt-32 rounded-3xl text-white w-full h-40" style="background-color:#468faf;">
      <div class="flex items-center">
        <div class="w-20 ml-2">
          <%= image_tag('logo.png', alt: 'Image de livre', class: "rounded-full") %>
        </div>
        <div class="text-white ml-6 text-3xl italic" style="">
          <h1>ModernScribe </h1>
        </div>
      </div>

      <div class="mr-6"style=" min-width:150px;">
      <%= link_to "Home", modern_home_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
    </div>
    
    <div class="mr-6"style=" min-width:150px;">
    <%= link_to "About Me", about_me_modern_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
    </div>
    </nav>


<br>
<h1> heeeeeeellllooo</h1>


<div class="flex flex-wrap mt-4 ">

<div class="mx-auto  border border-black border-4 rounded-2xl bg-white" style=" height:auto; width:auto; margin-left:25%">
<br>  

<h1 class="text-center"><strong  class="italic text-lg underline "> Title :</strong> <%= @article.title %></h1>

<h1 class="text-center"><strong class="italic text-lg underline "> Content :</strong> <%= @article.body %></h1>

  <div class="w-96 ">
  <div style="">
  <%= image_tag @article.image, style: "border-radius: 260px;" if @article.image.attached? %>
</div>



<h2 class="text-yellow-900 text-lg underline text-center">Comments:</h2>

<div class="max-w-md mx-auto" style="max-height: 90px; overflow-y: auto; margin-top: 10px;scrollbar-color: #dbbca8 #b68364; scrollbar-width:30px ">
  <% if @article.comments.any? %>
  <% @article.comments.each_with_index do |comment, index| %>
    <div>
    <p style="font-family: 'URW Chancery L', cursive; text-decoration: underline;"><strong>Comment <%= index + 1 %>:</strong></p>
    <%= render comment %>
    </div>
    <% end %>
  <% else %>
    <p class="text-center">There are no comments yet!</p>
  <% end %>
</div>






</div>


<br>


  <ul>
     <li><%= link_to " Edit ", edit_article_path(@article), data: { turbo_frame: "edit_article" },class: "border  border-4  rounded-full py-2 px-4 " ,style:"background-color: #d5bdaf;font-family: 'URW Chancery L', cursive;"%></li>
     <br>
     <li><%= link_to "Delete the article ?", article_path(@article), method: :delete, data: {   
                                                confirm: "Are you sure?"
                                                           } ,class: "border  border-4   rounded-full py-2 px-4 ",style:"background-color: #d5bdaf; text-color:#b36a5e;font-family: 'URW Chancery L', cursive;" %></li>
  </ul>
<br>
  </div>

<br>



  <div>

 

<div>

<div class="w-96 ml-14 mt-2" style="margin-left:-2%">
<%= image_tag('angel2.png', alt: 'Image de livre') %>
</div>



<div class="mx-auto  border border-black border-4 rounded-2xl " style=" height:400px; width:350px;margin-left:center">
<br>
    <h2 
    class="text-center -mt-22 italic text-2xl " style="text-shadow:20px 10px 5px black ;font-family: 'URW Chancery L', cursive ">Add a comment:</h2>
     <%= render 'comments/form' %>

  <div>


<div>


<div class="w-96 " style="margin-left: -1300px; margin-top: -490px">
<%= image_tag('angel.png', alt: 'Image de livre') %>
</div>



</body>