config/routes.rb
Rails.application.routes.draw do


  namespace :api do
    namespace :v1 do
      resources :articles
    end
  end

devise_for :users, controllers: { sessions: 'users/sessions' }

  root "articles#welcome"

  resources :articles do
    resources :comments
  end
  get 'welcome', to: 'welcome#index', as: 'welcome'


get '/about_me', to: 'articles#about_me', as: 'about_me'
get '/home', to: 'articles#index', as: 'home'




get 'modern_home', to: 'modern_home#index', as: 'modern_home'
get 'about_me_modern', to: 'modern_home#about_me_modern', as: 'about_me_modern'
get 'modern_articles/new', to: 'modern_home#new_modern_article', as: 'new_modern_article'
get 'show_modern/:id', to: 'modern_home#show_modern', as: 'show_modern'

get 'modern_articles', to: 'modern_articles#index', as: 'modern_articles'
get 'modern_articles/:id', to: 'modern_articles#show', as: 'modern_article'






get 'funny_home', to: 'funny_home#index', as: 'funny_home'
get 'about_me_funny', to: 'funny_home#about_me_funny', as: 'about_me_funny'
get 'new_funny_article', to: 'funny_home#new_funny_article', as: 'new_funny_article'
get 'show_funny/:id', to: 'funny_home#show_funny', as: 'show_funny'






end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  has_one_attached :image
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 5 }
end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < ApiController

    before_action:http_authenticate
    
    skip_before_action :verify_authenticity_token

    before_action :set_article, only: [:show, :update, :destroy]

    rescue_from ActiveRecord::RecordNotFound, with: :record_not_found



  
    def index
      articles = Article.all
      render json: articles
    end
  
    def show
      render json: @article
    end
  
    def create
      article = Article.new(article_params)
      if article.save
        render json: article, status: :created
      else
        render json: article.errors, status: :unprocessable_entity
      end
    end
  
    def update
      if @article.update(article_params)
        render json: @article
      else
        render json: @article.errors, status: :unprocessable_entity
      end
    end
  
    def destroy
      @article.destroy
      head :no_content
    end
  

    private
    
    def set_article
      @article = Article.find_by(id: params[:id])
      unless @article
        render json: { error: 'Article not found' }, status: :not_found
      end
    end
  
    def article_params
      params.require(:article).permit(:title, :body ,:status )
    end
  end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found 

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new 
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end


  def about_me
    @about_me_content = "Je suis [votre nom], et je suis passionné(e) par [vos intérêts]."
  end
 

 private

  def record_not_found
    flash[:alert] = 'Record not found'
    redirect_to root_path
  end

  def article_params
    params.require(:article).permit(:title, :body, :image, :status)
  end
end

app/helpers/api/v1/articles_helper.rb
module Api::V1::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <br>
    <div >
      <%= form.label :title , class:"italic text-2xl underline "%><br>
      <%= form.text_field :title , class:"border border-black rounded-2xl h-12 w-80"%>
      <% article.errors.full_messages_for(:title).each do |message| %>
        <div><%= message   %></div>
      <% end %>
    </div>
  <br>
    <div >
      <%= form.label :body , class:"italic text-2xl  underline"%><br>
      <%= form.text_area :body , class:"border border-black rounded-2xl w-80" %><br>
      <% article.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
   
   
    <br>
    <div>
      <%= form.label :status , class:"italic text-2xl  underline"%> 
      <br>
      <%= form.select :status, Visible::VALID_STATUSES, selected: article.status || 'public' , class:"border"%>
    
      </div>

      <br>
   

    <%= form.file_field :image %>

    <br>


    <br>
   
    <div  class= "border border-yellow-700 border-4 rounded-full py-2 px-4 w-40" style="box-shadow:2px 6px 6px 6px;">
      <%= form.submit%>
    </div>
 
    

  <% end %>
  


  

app/views/articles/about_me.html.erb
<body style="background-color: #f4f3ee;">

  <div class="flex flex-col items-stretch w-full">

    <nav class="flex justify-between items-center py-4 bg-yellow-800 -mt-32 rounded-3xl text-white w-full h-40">
    <div class="flex items-center">

    <% if current_user.profile_picture.attached? %>
    <%= image_tag current_user.profile_picture, alt: 'Image de profil', class: "rounded-full w-28 h-28" %>
    <% else %>
      <%= image_tag('profile.jpg', alt: 'Image par défaut', class: "rounded-full") %>
    <% end %>
    
      </div>
      
      <% if user_signed_in?  %>
    
      <div class="text-white -ml-60 text-3xl italic" style="font-family: 'URW Chancery L', cursive;">
        <%= "#{current_user.username} #{current_user.last_name}"%>
      </div>
      <div class="mr-6"style=" min-width:65px;">
      <%= link_to "Welcome ", welcome_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
      </div>

      <div class="mr-6"style=" min-width:65px;">
      <%= link_to "Home", home_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
    </div>
    
      <div class="mr-6"style=" min-width:120px;">
      <%= link_to "About Us", about_me_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
      </div>
      <%end%>
    </nav>


<br>

<div style="" >
<%= image_tag('blaka.png', alt: 'Image de livre',class:' mx-auto md:-ml-60', style:'margin-left:auto; width:533px') %>
</div>


<div class="border border-black border-4 rounded-2xl mx-auto " style="width: 400px; max-width: 580px; height:500px; box-shadow: 5px 5px 15px 5px; background-color: #faedcd;margin-top:-650px">
<div class="flex flex-col items-center justify-center h-full">
  <h1 class="text-black text-3xl italic" style="font-family: 'URW Chancery L', cursive;margin-left:-60px; margin-top:-90px " > Created by:</h1>  <br><br>
  <h1 class="text-black text-3xl text-left italic" style="font-family: 'URW Chancery L', cursive;"> Yassmine Ayari <br> A software <br> engineering student </h1>
</div>
</div>



<div >
<%= image_tag('richa.png', alt: 'Image de livre',class:'w-96 mx-auto rounded-xl ', style:'margin-left:20px; margin-top:-186px') %>
</div>


<div class="w-60 " style="margin-left:50%; margin-top:-185px">
<%= image_tag('tompony.png', alt: 'Image de livre',class:'w-96 mx-auto rounded-xl ', style:'margin-left:20px; margin-top:-186px') %>
</div>


  </div>

  </body>

app/views/articles/edit.html.erb
<body style="background-color: #f4f3ee;">

  <div class="flex flex-col items-stretch w-full">

    <nav class="flex justify-between items-center py-4 bg-yellow-800 -mt-32 rounded-3xl text-white w-full h-40">
      <div class="flex items-center">
        <div class="w-20 ml-2">
          <%= image_tag('butter.jpg', alt: 'Image de livre', class: "rounded-full") %>
        </div>
        <div class="text-white ml-6 text-3xl italic" style="font-family: 'URW Chancery L', cursive;">
          <h1>VintageScribe </h1>
        </div>
      </div>

      <div class="mr-6"style=" min-width:65px;">
      <%= link_to "Welcome ", welcome_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
      </div>

      <div class="mr-6"style=" min-width:65px;">
      <%= link_to "Home", home_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
    </div>
    
      <div class="mr-6"style=" min-width:120px;">
      <%= link_to "About Me", about_me_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
      </div>
    </nav>

  <br>

  <div class="mx-auto flex flex-col items-center justify-center border border-black rounded-2xl border-4" style="width: 600px;margin-top:30px">
  <h1 class="text-center italic text-3xl font-semibold" style="text-shadow: 20px 10px 5px black;">Edit Article</h1>
  <br>
  <%= render "form", article: @article %>
  <br>
</div>

<div style="margin-top: -560px; margin-left: 1100px;">
  <%= image_tag('deco.png', alt: 'Image de livre') %>
</div>

<div style="margin-top: -700px; margin-left: 350px; transform: scaleX(-1); transform-origin: left;">
  <%= image_tag('deco.png', alt: 'Image de livre') %>
</div>



</div>

</body>

app/views/articles/index.html.erb
<body style="background-color: #f4f3ee;">

  <div class="flex flex-col items-stretch">

    <nav class="flex justify-between items-center py-4 bg-yellow-800 -mt-32 rounded-3xl text-white h-40"  style="width:100% ; margin-left:auto">
    
    <div class="flex items-center">
    <% if user_signed_in? && current_user.profile_picture.attached? %>
      <%= image_tag current_user.profile_picture, alt: 'Image de profil', class: "rounded-full w-28 h-28" %>
    <% else %>
      <%= image_tag('profile.jpg', alt: 'Image par défaut', class: "rounded-full w-20 h-20 ml-2") %>
    <% end %>
  </div>
  
      
      <% if user_signed_in?  %>

      <div class="text-white  text-3xl italic" style="font-family: 'URW Chancery L', cursive; margin-left:-2%">
        <%= "#{current_user.username} #{current_user.last_name}"%>
      </div>

    
     <div class="mr-6"style=" min-width:65px;">
     <%= link_to "Welcome ", welcome_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
     </div>

     <div class="mr-6"style=" min-width:80px;">
     <%= link_to "New ", new_article_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
     </div>


     <div class="mr-6" style="min-width:115.6px" >
     <%= link_to "Edit Profile", edit_user_registration_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
     </div>

     <div class="mr-6" style="min-width:115.6px" >
       <%= link_to "Sign Out", destroy_user_session_path, method: :delete , class: "border border-white rounded-full py-2 px-4 text-white" , style:"; margin-right:auto; "  %>

      </div>


    <% else%> 
    
      <div class="mr-6">
       <%= link_to "Sign Up", new_user_registration_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
      </div>
  
      <div class="mr-6">
        <%= link_to "Sign In", new_user_session_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
      </div>

    <%end%>

    </nav>

    <div class="flex flex-wrap mt-4">
    <ul class="flex-2 flex flex-wrap">
      <% @articles.each do |article| %>
        <% unless article.archived? %>
          <li class="inline-block border border-black rounded-2xl p-4 mb-8 mr-4 ml-14 mt-8 bg-white" style="box-shadow: 5px 5px 5px 5px; width: 400px; position: relative;">
            <div style="position: absolute; top: 0; left: 50%; transform: translateX(-50%);">
              <%= image_tag('tompon1.png', alt: 'Image de livre', style: "height: 100px; margin-left:180px;margin-top:-50px; width:150px; ") %>
            </div>
            <%= link_to article.title, article_path(article), class: "text-xl text-center block" , style: "font-family: 'URW Chancery L', cursive;"%>
            <% if article.image.attached? %>
              <%= image_tag article.image, class: "rounded-3xl mx-auto", style: "max-height: 300px; display: block; margin: 0 auto;" %>
            <% end %>
  
            <div class="text-gray-700 text-sm text-center">
              <% if params[:full] == 'true' %>
                <%= article.body %>
              <% else %>
                <%= truncate(article.body, length: 20) %><br>
                <%= link_to 'Show More', article_path(article, full: true), class: "font-semibold text-base border border-black box-border rounded-2xl", style: "font-family: 'URW Chancery L', cursive; display: block; margin: 0 auto;" %>
              <% end %>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
  

  <div class="w-96 ml-6 mt-8">
    <%= image_tag('fille.png', alt: 'Image de livre') %>
  </div>


</body>

app/views/articles/new.html.erb
<body style="background-color: #f4f3ee;">

<div class="flex flex-col items-stretch w-full">
<nav class="flex justify-between items-center py-4 bg-yellow-800 -mt-32 rounded-3xl text-white">
<div class="flex items-center">

<% if current_user.profile_picture.attached? %>
<%= image_tag current_user.profile_picture, alt: 'Image de profil', class: "rounded-full w-28 h-28" %>
<% else %>
  <%= image_tag('profile.jpg', alt: 'Image par défaut', class: "rounded-full") %>
<% end %>

  </div>
  
  <% if user_signed_in?  %>

  <div class="text-white -ml-60 text-3xl italic" style="font-family: 'URW Chancery L', cursive;">
    <%= "#{current_user.username} #{current_user.last_name}"%>
  </div>
  <div class="mr-6"style=" min-width:65px;">
  <%= link_to "Welcome ", welcome_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
  </div>

  <div class="mr-6"style=" min-width:65px;">
  <%= link_to "Home", home_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
</div>


<div class="mr-6"style=" min-width:120px;">
<%= link_to "About Us", about_me_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
</div>
<%end%>

</nav>
<br>

<div class=" border border-black  border-4 rounded-2xl mx-auto  " style=" width:600px; height:500px; box-shadow:5px 5px 15px 5px ">
<div class="flex flex-col items-center justify-center h-full">

<h1 class="text-center -mt-22 italic text-3xl font-semibold " style="text-shadow:20px 10px 5px black ;font-family: 'URW Chancery L', cursive;">New Article</h1>

 <%= render "form", article: @article %>

 </div>

 </div>



  <div class="w-96 ml-6 -mt-6">
    <%= image_tag('fille.png', alt: 'Image de livre',class:"rounded-3xl") %>
  </div>



</div>
</body>

app/views/articles/show.html.erb
<body style="background-color: #f4f3ee;">

  <div class="flex flex-col items-stretch w-full">

    <nav class="flex justify-between items-center py-4 bg-yellow-800 -mt-32 rounded-3xl text-white w-full h-40">
    <div class="flex items-center">

    <% if current_user.profile_picture.attached? %>
    <%= image_tag current_user.profile_picture, alt: 'Image de profil', class: "rounded-full w-28 h-28" %>
    <% else %>
      <%= image_tag('profile.jpg', alt: 'Image par défaut', class: "rounded-full") %>
    <% end %>

      </div>
      
      <% if user_signed_in?  %>

      <div class="text-white -ml-60 text-3xl italic" style="font-family: 'URW Chancery L', cursive;">
        <%= "#{current_user.username} #{current_user.last_name}"%>
      </div>

      <div class="mr-6"style=" min-width:65px;">
      <%= link_to "Welcome ", welcome_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
      </div>

      <div class="mr-6"style=" min-width:65px;">
      <%= link_to "Home", home_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
    </div>
    
      <div class="mr-6"style=" min-width:120px;">
      <%= link_to "About US", about_me_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
      </div>

    <% else%> 
    
      <div class="mr-6">
       <%= link_to "Sign Up", new_user_registration_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
      </div>
  
      <div class="mr-6">
        <%= link_to "Sign In", new_user_session_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
      </div>

    <%end%>

    </nav>

<br>


<div class="flex flex-wrap mt-4 ">

<div class="mx-auto  border border-black border-4 rounded-2xl bg-white" style=" height:auto; width:auto; margin-left:25%">
<br>  

<h1 class="text-center"><strong  class="italic text-lg underline "> Title :</strong> <%= @article.title %></h1>

<h1 class="text-center"><strong class="italic text-lg underline "> Content :</strong> <%= @article.body %></h1>

  <div class="w-96 ">
  <div style="">
  <%= image_tag @article.image, style: "border-radius: 260px;" if @article.image.attached? %>
</div>



<h2 class="text-yellow-900 text-lg underline text-center">Comments:</h2>

<div class="max-w-md mx-auto" style="max-height: 90px; overflow-y: auto; margin-top: 10px;scrollbar-color: #dbbca8 #b68364; scrollbar-width:30px ">
  <% if @article.comments.any? %>
  <% @article.comments.each_with_index do |comment, index| %>
    <div>
    <p style="font-family: 'URW Chancery L', cursive; text-decoration: underline;"><strong>Comment <%= index + 1 %>:</strong></p>
    <%= render comment %>
    </div>
    <% end %>
  <% else %>
    <p class="text-center">There are no comments yet!</p>
  <% end %>
</div>






</div>


<br>


  <ul>
     <li><%= link_to " Edit ", edit_article_path(@article), data: { turbo_frame: "edit_article" },class: "border  border-4  rounded-full py-2 px-4 " ,style:"background-color: #d5bdaf;font-family: 'URW Chancery L', cursive;"%></li>
     <br>
     <li><%= link_to "Delete the article ?", article_path(@article), method: :delete, data: {   
                                                confirm: "Are you sure?"
                                                           } ,class: "border  border-4   rounded-full py-2 px-4 ",style:"background-color: #d5bdaf; text-color:#b36a5e;font-family: 'URW Chancery L', cursive;" %></li>
  </ul>
<br>
  </div>

<br>



  <div>

 

<div>

<div class="w-96 ml-14 mt-2" style="margin-left:-2%">
<%= image_tag('angel2.png', alt: 'Image de livre') %>
</div>



<div class="mx-auto  border border-black border-4 rounded-2xl " style=" height:400px; width:350px;margin-left:center">
<br>
    <h2 
    class="text-center -mt-22 italic text-2xl " style="text-shadow:20px 10px 5px black ;font-family: 'URW Chancery L', cursive ">Add a comment:</h2>
     <%= render 'comments/form' %>

  <div>


<div>


<div class="w-96 " style="margin-left: -1300px; margin-top: -490px">
<%= image_tag('angel.png', alt: 'Image de livre') %>
</div>



</body>

app/views/articles/welcome.html.erb
<body style="background-color:#f4f3ee">

  <nav class="bg-gray-800 p-4 fixed w-full  " style="top: 0; width: 105%; margin-left: -10.6%; height: 100px;">
     


    <div class="container-fluid mx-auto flex  items-center" style="margin-left:60%; min-width:600px; margin-top:1.3%">  
    
    
    <% if user_signed_in?  %>

    <div class="mr-6" style="min-width:100px" >
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete ,class: "border border-white rounded-full py-2 px-4 text-white"%>
  </div>

  <div class="mr-6" style="min-width:115.6px" >
    <%= link_to "Edit Profile", edit_user_registration_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
 </div>

    
  <% else %> 
    
    <div class="mr-6">
      <%= link_to "Sign Up", new_user_registration_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
    </div>
  
    <div class="mr-6">
      <%= link_to "Sign In", new_user_session_path, class: "border border-white rounded-full py-2 px-4 text-white" %>
    </div>
  
  <% end %>
  
    
    </div>
  </nav>

 
    <% if user_signed_in?  %>
    <div class="container mx-auto my-8 p-8 shadow-md rounded-md bg-white mt-20" >

    <h1 class="text-4xl font-bold mb-4 text-center"> Welcome to our website! </h1>

    <h2 class="text-4xl font-bold mb-4 text-center" > choose the theme that you like   </h2>




    <div class="container mx-auto my-8 p-8 shadow-md rounded-md bg-white mt-50 w-96 flex"style="width:50%">
    <div class="text-4xl font-bold mb-4 text-center" style="background-color: #ffffff; margin: 0 20px; padding: 20px;">
            <%= link_to "Vintage Theme", home_path, class: "border border-white rounded-full py-2 px-4 text-black" %>
    </div>
  </div>

   
  <div class="container mx-auto my-8 p-8 shadow-md rounded-md bg-white mt-50 w-96 flex" style="width:50%">
  <div class="text-4xl font-bold mb-4 text-center" style="background-color: #ffffff; margin: 0 20px; padding: 20px;">
    <%= link_to "Modern Theme", modern_home_path, class: "border border-white rounded-full py-2 px-4 text-black" %>
  </div>
</div>


  
<div class="container mx-auto my-8 p-8 shadow-md rounded-md bg-white mt-50 w-96 flex"style="width:50%">
<div class="text-4xl font-bold mb-4 text-center" style="background-color: #ffffff; margin: 0 20px; padding: 20px;">
        <%= link_to "Funny Theme", funny_home_path, class: "border border-white rounded-full py-2 px-4 text-black" %>
</div>
</div>

</div>
   
<% else %> 
<div class="container mx-auto my-8 p-8 shadow-md rounded-md bg-white mt-60" >
<h1 class="text-4xl font-bold mb-4 text-center" style=""> Welcome to our website! </h1>
<p class="text-2xl text-red-900 font-bold mb-4 text-center">You are required to create an account in order to access our website. </p>
</div>

<% end %>





    


</body>